### ISSUE TITLE
In-flight cancellation and issuing of clearances

### ISSUE THREAD

**Issue by JT8D-17** [markcellis/X-ATC-Chatter#6]
- In-flight clearance cancellation is just a nicer way to wrap the "Cancel Flight Plan" button. Cancelling after having received clearance would trigger a "[Agency], [Callsign] would like to cancel flight plan to [destination]." request with confirmation by ATC "[Callsign], flight plan cancelled. Squawk 1200.". When on the ground, the controller may also suggest contacting the agency issuing clearances for a new one.
- As of now, when requesting a flight plan clearance in flight, you'll have to go through the entire motion of having to request startup, taxi, takeoff, etc. and all the associated conversations just to end up with the exact same center, approach or departure controller. To discriminate between clearance requests prior to takeoff and in-flight, simply add an "Is on ground?" check and, if the aircraft is airborne, hide the departure part of the flight planner, adapt the clearance request accordingly and forward the flight state to "airborne" so that the new clearance request conversation can directly be had with the current agency.

**Comment by markcellis** [comment]
I think this maybe accomplished now with the new Divert feature in 1.7.1 Beta 10

**Comment by markcellis** [comment]
So now that we have the ability to choose an alternate airport while on a flight do we still need this? One possible scenario is to cancel IFR and continue to your destination VFR.

**Comment by markcellis** [comment]
I think this is solved in 1.7.1

**Comment by JT8D-17** [comment]
Need to reopen this as of 1.7.2 it is still necessary to do the entire ground routine (startup, taxi, takeoff, departure) when requesting clearance in flight.

**Comment by markcellis** [comment]
I agree, I have had a bunch of requests to allow starting Simple ATC after departure.
