### ISSUE TITLE
Support for SID/STAR and approach type names

### ISSUE THREAD

**Issue by JT8D-17** [markcellis/X-ATC-Chatter#8]
SID names:
- SIDs should be treated like departure runways, with a simple text box provided for SID name input by the user while on the ground.
- ATC and readback text only need to be amended with "departure via [SID name]" in the clearance.
- If the text box remains empty, no SID is used in the clearance comms exchange.

STAR names:
- Provide an input box for the STAR's name during the cruise phase of the flight and a "Request STAR approach" button.
- If a STAR name is provided and the user hits the "Request STAR Approach" button, ATC automatically clears the user aircraft for the provided approach and instructs the user to descend at pilot's discretion.
- The handover to approach includes a "[Callsign], continue via [STAR]"

Approach type names:
- Prior to the approach phase, when runway selection is still possible, there should be a dropdown with common approach types, e.g. "Visual", "ILS", "RNAV", "VOR", "VOR-DME", "NDB", etc.
- The selected approach type is part of the clearance, e.g. "...cleared for ILS approach, runway 25L, descend at pilot's discretion."3

Optional: 
- Automatically generate a llist of available SID/STAR and approach names for the departure and destination airports.
- Data is stored in `X-Plane 11/Resources/default data/CIFP` (default) or `X-Plane 11/Custom Data/CIFP` (Navigraph data)
- File format specification: https://developer.x-plane.com/wp-content/uploads/2019/01/XP-CIFP1101-Spec.pdf

**Comment by markcellis** [comment]
First cut is available in 1.7.1 Beta 7

**Comment by markcellis** [comment]
Done in Beta 8
