### ISSUE TITLE
Support Weather/Route Deviations

### ISSUE THREAD

**Issue by JT8D-17** [markcellis/X-ATC-Chatter#9]
Because some situations may call for a temporary deviation from the assigned flight plan, e.g. due to weather or traffic, it'd be nice to have a "Report Route Deviation" button while in flight. Ideally, this would be combined with a selector with a reason.

"[Agency], [Callsign], needs to leave the route for [weather/traffic/terrain]."
- "[Callsign] roger, report when back on your assigned flight plan."

When a route deviation was reported, there'll be a "Report Back On Route" button.

"[Agency], [Callsign] is back on the assigned flight plan."
- "[Callsign], roger, thank you."

**Comment by markcellis** [comment]
Added in 1.7.1 beta 12
